name: Continuous Integration
on:
  push:
    branches: [ "feature/*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Executando teste unitarios
      run: make tests

    - name: Build
      run: make build

